name: helmbroker
home: https://github.com/drycc/helmbroker
apiVersion: v2
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
  - name: gateway
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
  - name: rabbitmq
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
description: Drycc Workflow helmbroker.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
