imageOrg: "drycc"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
imagePullPolicy: "Always"
replicas: 1
# limitsCpu: "100m"
# limitsMemory: "50Mi"

## config the helm-broker repositories
repositories:
- name: drycc-helm-broker
  url: https://github.com/drycc/addons/releases/download/latest/index.yaml

celeryReplicas: 1

# broker_credentials:
# Optional Usernames and passwords that will be required to communicate with service broker
username: admin
password: admin

environment:
  RESERVED_NAMES: "drycc, drycc-helmbroker"
  # HELMBROKER_CELERY_BROKER: ""
  # HELMBROKER_CELERY_BACKEND: ""

api:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-helmbroker"

celery:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-helmbroker-celery"

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 5Gi
  storageClass: ""
  volumeName: ""

ingressClass: ""
# A domain name consists of one or more parts.
# Periods (.) are used to separate these parts.
# Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
# It must start and end with a lowercase letter or digit.
clusterDomain: "cluster.local"
# The public resolvable hostname to build your cluster with.
#
# This will be the hostname that is used to build endpoints such as "drycc-helmbroker.$HOSTNAME"
platformDomain: ""
# Whether cert_manager is enabled to automatically generate helmbroker certificates
certManagerEnabled: true