imageOrg: "drycc-addons"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
imagePullPolicy: "Always"
replicas: 1
# limitsCpu: "100m"
# limitsMemory: "50Mi"

## config the helm-broker repositories
repositories:
- name: drycc-helm-broker
  url: https://github.com/drycc/addons/releases/download/latest/index.yaml

celeryReplicas: 1

# broker_credentials:
# Optional Usernames and passwords that will be required to communicate with service broker
username: admin
password: admin

# Configuring this will no longer use the built-in rabbitmq component
rabbitmqUrl: ""

# Any custom controller environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment:
  # DRYCC_DEBUG: true
  # HELMBROKER_ROOT: /etc/helmbroker

api:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-helmbroker"

celery:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-helmbroker-celery"

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 5Gi
  storageClass: ""
  volumeName: ""

global:
  # Set the location of Workflow's rabbitmq instance
  # Valid values are:
  # - on-cluster: Run Rabbitmq within the Kubernetes cluster
  # - off-cluster: Run Rabbitmq outside the Kubernetes cluster (configure in controller section)
  rabbitmqLocation: "on-cluster"
  # Enable usage of RBAC authorization mode
  #
  # Valid values are:
  # - true: all RBAC-related manifests will be installed (in case your cluster supports RBAC)
  # - false: no RBAC-related manifests will be installed
  rbac: true
  # Please check `kubernetes.io/ingress.class`
  # The cert-manager component must be installed
  # If you want to use HTTPSEnforced or allowlist functions, you must specify:
  # - nginx
  # - traefik
  # Only the above options have been supported so far
  ingressClass: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc-helmbroker.$HOSTNAME"
  platformDomain: ""
  # Whether cert_manager is enabled to automatically generate helmbroker certificates
  certManagerEnabled: true