imageOrg: "drycc-addons"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
imagePullPolicy: "Always"
replicas: 1
# limitsCpu: "100m"
# limitsMemory: "50Mi"

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

## config the helm-broker repositories
repositories:
  - name: drycc-helm-broker
    url: https://github.com/drycc/addons/releases/download/latest/index.yaml

celeryReplicas: 1

# broker_credentials:
# Optional Usernames and passwords that will be required to communicate with service broker
username: admin
password: admin

# Configuring this will no longer use the built-in valkey component
valkeyUrl: ""

# Any custom controller environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment:
  # HELMBROKER_DEBUG: true
  # HELMBROKER_CONFIG_ROOT: /etc/helmbroker

api:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
      - "true"
  podAffinityPreset:
    type: ""
    extraMatchLabels:
      security: "drycc-security"
  podAntiAffinityPreset:
    type: "soft"
    extraMatchLabels:
      app: "drycc-helmbroker"

celery:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
      - "true"
  podAffinityPreset:
    type: ""
    extraMatchLabels:
      security: "drycc-security"
  podAntiAffinityPreset:
    type: "soft"
    extraMatchLabels:
      app: "drycc-helmbroker-celery"

# Default override of addon values
addonValues: {}

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 5Gi
  storageClass: ""
  volumeName: ""

global:
  # Set the location of Workflow's valkey instance
  # Valid values are:
  # - on-cluster: Run Valkey within the Kubernetes cluster
  # - off-cluster: Run Valkey outside the Kubernetes cluster (configure in controller section)
  valkeyLocation: "on-cluster"
  # Enable usage of RBAC authorization mode
  #
  # Valid values are:
  # - true: all RBAC-related manifests will be installed (in case your cluster supports RBAC)
  # - false: no RBAC-related manifests will be installed
  rbac: true
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
