FROM docker.io/library/python:3.9-alpine

COPY requirements.txt /app/requirements.txt

ENV PATH="/app/.venv/bin:${PATH}"

COPY . /app

WORKDIR /app

RUN apk add --update --virtual .build-deps \
    musl-dev \
    openssl-dev \
  && python3 -m venv /app/.venv \
  && source /app/.venv/bin/activate \
  && pip3 install --disable-pip-version-check --no-cache-dir -r /app/requirements.txt \
  && pip3 install --disable-pip-version-check --no-cache-dir -r /app/dev_requirements.txt \
  && find /app/.venv /usr/local -type f -executable ! -path '*/cryptography*' -exec scanelf --needed --nobanner --format '%n#p' '{}' ';' \
    | tr ',' '\n' \
    | sort -u \
    | awk 'system("[[ -e /app/.venv/lib/" $1 " || -e /usr/local/lib/" $1 " ]]") == 0 { next } { print "so:" $1 }' \
    | xargs -rt apk add --no-cache --virtual .python-rundeps \
  && apk add --update --virtual .helmbroker-rundeps \
    $runDeps \
    git \
    ca-certificates \
    su-exec \
    bash \
    shadow \
    curl \
  && apk del .build-deps \
  && chmod +x /app/bin/* \
  && /app/bin/install
COPY . /app

ENV PATH /app/.venv/bin:/app/bin:$PATH
CMD ["/app/bin/boot"]
EXPOSE 8000
