FROM docker.io/library/python:3.9-alpine

COPY requirements.txt /app/requirements.txt

ENV PATH="/app/.venv/bin:${PATH}"

COPY . /app

WORKDIR /app

RUN apk add --update --virtual .build-deps \
    musl-dev \
    openssl-dev \
  && python3 -m venv /app/.venv \
  && pip3 install --disable-pip-version-check --no-cache-dir -r /app/requirements.txt \
  && pip3 install --disable-pip-version-check --no-cache-dir -r /app/dev_requirements.txt \
  && runDeps="$( \
    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
    | tr ',' '\n' \
    | sort -u \
    | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )" \
  && apk add --update --virtual .helmbroker-rundeps \
    $runDeps \
    git \
    ca-certificates \
    su-exec \
    bash \
    shadow \
    curl \
  && apk del .build-deps \
  && chmod +x /app/bin/* \
  && /app/bin/install
COPY . /app

CMD ["/app/bin/boot"]
EXPOSE 5000
