apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-helmbroker
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-helmbroker
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: drycc-helmbroker
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.api.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.api.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.api.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.api.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.api.nodeAffinityPreset.type "key" .Values.api.nodeAffinityPreset.key "values" .Values.api.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-helmbroker
      initContainers:
        - name: drycc-helmbroker-init
          image: registry.drycc.cc/drycc/python-dev:latest
          imagePullPolicy: {{.Values.imagePullPolicy}}
          args:
          - netcat
          - -v
          - -u
          - $(HELMBROKER_REDIS_URL),$(HELMBROKER_RABBITMQ_URL)
        {{- include "helmbroker.envs" . | indent 10 }}
        - name: drycc-helmbroker-fetch
          image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/helmbroker:{{.Values.imageTag}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          args:
          - /bin/bash
          - -c
          - python -m helmbroker.database.fetch
          {{- include "helmbroker.envs" . | indent 10 }}
          {{- include "helmbroker.volumeMounts" . | indent 10 }}
      containers:
      - name: drycc-helmbroker
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/helmbroker:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 8 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 8 }}
        {{- end }}
        {{- if not .Values.diagnosticMode.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 5
        {{- end }}
        ports:
          - containerPort: 8000
            name: http
        {{- include "helmbroker.limits" . | indent 8 }}
        {{- include "helmbroker.envs" . | indent 8 }}
        {{- include "helmbroker.volumeMounts" . | indent 8 }}
      {{- include "helmbroker.volumes" . | indent 6 }}
