apiVersion: batch/v1
kind: CronJob
metadata:
  name: drycc-helmbroker-cronjob-daily
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-helmbroker
          containers:
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/helmbroker:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-helmbroker-cleaner
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            args:
            - /bin/bash
            - -c
            - python -m helmbroker.cleaner
            {{- end }}
            {{- include "helmbroker.envs" . | indent 12 }}
            {{- include "helmbroker.volumeMounts" . | indent 12 }}
          {{- include "helmbroker.volumes" . | indent 10 }}