kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc:drycc-helmbroker
  labels:
    app: drycc-helmbroker
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drycc:drycc-helmbroker
subjects:
- kind: ServiceAccount
  name: drycc-helmbroker
  namespace: {{ .Release.Namespace }}
