{{- if .Values.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-helmbroker
spec:
  secretName: drycc-helmbroker-certificate-auto
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc-helmbroker.{{ .Values.platformDomain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
