apiVersion: v1
kind: Service
metadata:
  name: drycc-helmbroker
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: drycc-helmbroker
