apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-helmbroker-celery
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.celeryReplicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-helmbroker-celery
  template:
    metadata:
      labels:
        app: drycc-helmbroker-celery
    spec:
      {{- include "common.affinities.nodes.soft" (dict "key" "app" "values" (list "drycc-helmbroker-celery")) | indent 6 }}
      serviceAccount: drycc-helmbroker
      containers:
        - name: drycc-helmbroker-celery
          image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/helmbroker:{{.Values.imageTag}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          args:
          - /bin/bash
          - -c
          - celery -A helmbroker worker --autoscale=32,1 --loglevel=info
          {{- include "helmbroker.limits" . | indent 10 }}
          {{- include "helmbroker.envs" . | indent 10 }}
          {{- include "helmbroker.volumeMounts" . | indent 10 }}
      {{- include "helmbroker.volumes" . | indent 6 }}
