apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-helmbroker-celery
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: {{ .Values.celery_replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-helmbroker-celery
  template:
    metadata:
      labels:
        app: drycc-helmbroker-celery
    spec:
      serviceAccount: drycc-helmbroker
      containers:
        - name: drycc-helmbroker-celery
          image: {{.Values.image_registry}}/{{.Values.image_org}}/helmbroker:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
          command:
            - /bin/bash
            - -c
          args:
            - celery -A api worker --autoscale=32,1 --loglevel=info
          {{- include "helmbroker.limits" . | indent 10 }}
          {{- include "helmbroker.envs" . | indent 10 }}
          {{- include "helmbroker.volumeMounts" . | indent 10 }}
      {{- include "helmbroker.volumes" . | indent 6 }}